version: '3.8'

services:
  web:
    build: .
    container_name: intake
    expose:
      - "8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - POSTGRES_NAME=shuttle_system_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - VIRTUAL_HOST=intake.justcodeit.ai
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=intake.justcodeit.ai
    networks:
      - nginx-proxy-manager_npm_network
      - default
    restart: unless-stopped
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15
    container_name: intake_db
    environment:
      - POSTGRES_DB=shuttle_system_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  nginx-proxy-manager_npm_network:
    external: true
  default: