# Generated by Django 5.1.5 on 2025-01-30 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('problem_statement', models.TextField()),
                ('objectives', models.TextField()),
                ('scope', models.TextField()),
                ('out_of_scope', models.TextField()),
                ('start_date', models.DateField()),
                ('estimated_end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('project_manager', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('likelihood', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impact', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('mitigation_strategy', models.TextField()),
                ('owner', models.CharField(max_length=100)),
                ('status', models.CharField(default='IDENTIFIED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('stakeholder_type', models.CharField(choices=[('PARKING_OWNER', 'Parking Lot Owner'), ('SHUTTLE_OPERATOR', 'Shuttle Operator'), ('CUSTOMER', 'Customer'), ('LOCAL_GOVT', 'Local Government'), ('BUSINESS', 'Local Business'), ('OTHER', 'Other')], max_length=20)),
                ('influence_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirement_type', models.CharField(choices=[('FUNCTIONAL', 'Functional'), ('NON_FUNCTIONAL', 'Non-Functional'), ('BUSINESS', 'Business'), ('REGULATORY', 'Regulatory')], max_length=20)),
                ('priority', models.CharField(choices=[('MUST', 'Must Have'), ('SHOULD', 'Should Have'), ('COULD', 'Could Have'), ('WONT', "Won't Have")], max_length=10)),
                ('acceptance_criteria', models.TextField()),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stakeholders', models.ManyToManyField(related_name='requirements', to='project_management.stakeholder')),
            ],
        ),
    ]
