# Generated by Django 5.1.5 on 2025-01-31 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('operator_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('implementation_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_name', models.CharField(max_length=100)),
                ('respondent_email', models.EmailField(max_length=254)),
                ('pain_points', models.TextField(help_text='Describe your main challenges with the current shuttle system')),
                ('desired_features', models.TextField(help_text='What features would you like to see in the new system?')),
                ('frequency_of_use', models.CharField(help_text='How often do you use shuttle services?', max_length=50)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='requirements_gathering.customersurvey')),
            ],
        ),
        migrations.CreateModel(
            name='RegulatoryCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('authority', models.CharField(max_length=100)),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('in_progress', 'In Progress'), ('not_applicable', 'Not Applicable')], max_length=20)),
                ('verification_date', models.DateField()),
                ('next_review_date', models.DateField()),
                ('documentation', models.TextField(help_text='List all relevant documentation and certificates')),
                ('action_items', models.TextField(blank=True)),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('survey', 'Customer Survey'), ('operational', 'Operational Requirement'), ('regulatory', 'Regulatory Document')], max_length=20)),
                ('file', models.FileField(upload_to='requirements_docs/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
