# Generated by Django 5.1.5 on 2025-01-31 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('component_type', models.CharField(choices=[('s3', 'Amazon S3'), ('lambda', 'AWS Lambda'), ('rds', 'Amazon RDS'), ('api_gateway', 'API Gateway'), ('cognito', 'Amazon Cognito'), ('cloudfront', 'CloudFront'), ('route53', 'Route 53'), ('vpc', 'VPC'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('configuration', models.JSONField(help_text='AWS configuration details in JSON format')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='planned', max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dependencies', models.ManyToManyField(blank=True, to='system_design.awscomponent')),
            ],
        ),
        migrations.CreateModel(
            name='ArchitectureDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('diagram_type', models.CharField(choices=[('high_level', 'High Level Architecture'), ('detailed', 'Detailed Architecture'), ('network', 'Network Diagram'), ('data_flow', 'Data Flow Diagram')], max_length=20)),
                ('description', models.TextField()),
                ('diagram_file', models.FileField(upload_to='architecture_diagrams/')),
                ('version', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('aws_components', models.ManyToManyField(related_name='diagrams', to='system_design.awscomponent')),
            ],
        ),
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], max_length=10)),
                ('description', models.TextField()),
                ('request_schema', models.JSONField(help_text='Expected request format in JSON')),
                ('response_schema', models.JSONField(help_text='Expected response format in JSON')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('aws_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='system_design.awscomponent')),
            ],
        ),
        migrations.CreateModel(
            name='SystemIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('integration_type', models.CharField(choices=[('payment', 'Payment Gateway'), ('gps', 'GPS Tracking'), ('notification', 'Notification Service'), ('analytics', 'Analytics Service'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('provider', models.CharField(max_length=100)),
                ('api_documentation', models.URLField(blank=True)),
                ('configuration', models.JSONField(help_text='Integration configuration details')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='planned', max_length=50)),
                ('aws_components', models.ManyToManyField(related_name='integrations', to='system_design.awscomponent')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UIComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('component_type', models.CharField(choices=[('customer_web', 'Customer Web Interface'), ('customer_mobile', 'Customer Mobile Interface'), ('operator_dashboard', 'Operator Dashboard'), ('admin_panel', 'Admin Panel')], max_length=20)),
                ('description', models.TextField()),
                ('wireframe_url', models.URLField(blank=True, help_text='Link to wireframe/mockup')),
                ('design_file', models.FileField(blank=True, upload_to='ui_designs/')),
                ('features', models.JSONField(help_text='List of features and their descriptions')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
