# Generated by Django 3.2.14 on 2025-01-30 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SWOTAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.TextField()),
                ('weaknesses', models.TextField()),
                ('opportunities', models.TextField()),
                ('threats', models.TextField()),
                ('analysis_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_initiation.project')),
            ],
        ),
        migrations.CreateModel(
            name='StakeholderAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakeholder_name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('influence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('interest', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('engagement_strategy', models.CharField(choices=[('MANAGE_CLOSELY', 'Manage Closely'), ('KEEP_SATISFIED', 'Keep Satisfied'), ('KEEP_INFORMED', 'Keep Informed'), ('MONITOR', 'Monitor')], max_length=20)),
                ('communication_frequency', models.CharField(max_length=100)),
                ('contact_info', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_initiation.project')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_description', models.TextField()),
                ('likelihood', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('impact', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('mitigation_strategy', models.TextField()),
                ('contingency_plan', models.TextField()),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identified'), ('ASSESSED', 'Assessed'), ('MITIGATED', 'Mitigated'), ('CLOSED', 'Closed')], default='IDENTIFIED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_initiation.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('responsibilities', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_initiation.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('deliverables', models.TextField()),
                ('dependencies', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_initiation.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField()),
                ('objectives', models.TextField()),
                ('scope_included', models.TextField()),
                ('scope_excluded', models.TextField()),
                ('deliverables', models.TextField()),
                ('success_criteria', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timeline_start', models.DateField()),
                ('timeline_end', models.DateField()),
                ('approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_charters', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_initiation.project')),
            ],
        ),
        migrations.CreateModel(
            name='KickoffMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('agenda', models.TextField()),
                ('presentation_materials', models.TextField()),
                ('meeting_notes', models.TextField()),
                ('action_items', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_initiation.project')),
            ],
        ),
        migrations.CreateModel(
            name='FeasibilityStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_feasibility', models.TextField()),
                ('technical_status', models.CharField(choices=[('FEASIBLE', 'Feasible'), ('NOT_FEASIBLE', 'Not Feasible'), ('NEEDS_INVESTIGATION', 'Needs Further Investigation')], max_length=20)),
                ('economic_feasibility', models.TextField()),
                ('economic_status', models.CharField(choices=[('FEASIBLE', 'Feasible'), ('NOT_FEASIBLE', 'Not Feasible'), ('NEEDS_INVESTIGATION', 'Needs Further Investigation')], max_length=20)),
                ('operational_feasibility', models.TextField()),
                ('operational_status', models.CharField(choices=[('FEASIBLE', 'Feasible'), ('NOT_FEASIBLE', 'Not Feasible'), ('NEEDS_INVESTIGATION', 'Needs Further Investigation')], max_length=20)),
                ('legal_feasibility', models.TextField()),
                ('legal_status', models.CharField(choices=[('FEASIBLE', 'Feasible'), ('NOT_FEASIBLE', 'Not Feasible'), ('NEEDS_INVESTIGATION', 'Needs Further Investigation')], max_length=20)),
                ('recommendations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_initiation.project')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField()),
                ('objectives', models.TextField()),
                ('benefits', models.TextField()),
                ('costs', models.TextField()),
                ('roi_analysis', models.TextField()),
                ('assumptions', models.TextField()),
                ('constraints', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_initiation.project')),
            ],
        ),
    ]
